import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.HashMap;

import org.opencv.core.*;
import org.opencv.core.Core.*;
import org.opencv.features2d.FeatureDetector;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;

/**
* HatchTargetPipelineLifecam class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class Lifecam5000HatchTargetPipeline extends HatchTargetPipelineLifecam implements IHatchTargetPipeline {

}

